create extension if not exists postgis with schema extensions;

create table public.groups (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  leader_id uuid not null,
  constraint groups_name_not_blank check (char_length(btrim(name)) > 0)
);

create table public.farmers (
  id uuid primary key default gen_random_uuid(),
  first_name text not null,
  last_name text not null,
  tel text not null,
  address text not null,
  province_id bigint not null,
  district_id bigint not null,
  subdistrict_id bigint not null,
  group_id uuid references public.groups (id) on delete restrict,
  delivered_kg integer not null default 0,
  avatar_url text,
  constraint farmers_name_not_blank check (char_length(btrim(first_name)) > 0 and char_length(btrim(last_name)) > 0),
  constraint farmers_address_not_blank check (char_length(btrim(address)) > 0),
  constraint farmers_place_ids_positive check (province_id > 0 and district_id > 0 and subdistrict_id > 0),
  constraint farmers_tel_format check (tel ~ '^0[689][0-9]-[0-9]{3}-[0-9]{4}$'),
  constraint farmers_tel_unique unique (tel),
  constraint farmers_delivered_kg_nonnegative check (delivered_kg >= 0),
  constraint farmers_avatar_url_http check (avatar_url is null or avatar_url ~ '^https?://')
);

alter table public.groups
  add constraint groups_leader_fkey
  foreign key (leader_id) references public.farmers (id) on delete restrict
  deferrable initially deferred;

alter table public.groups
  add constraint groups_one_leader unique (leader_id);

create table public.roles (
  id bigint generated by default as identity primary key,
  name text not null,
  constraint roles_name_not_blank check (char_length(btrim(name)) > 0),
  constraint roles_name_unique unique (name)
);

create table public.varieties (
  id bigint generated by default as identity primary key,
  name text not null,
  constraint varieties_name_not_blank check (char_length(btrim(name)) > 0),
  constraint varieties_name_unique unique (name)
);

create table public.plots (
  id uuid primary key default gen_random_uuid(),
  farmer_id uuid not null references public.farmers (id) on delete restrict,
  name text not null,
  area_rai numeric(12, 2) not null,
  province_id bigint not null,
  district_id bigint not null,
  subdistrict_id bigint not null,
  boundary extensions.geometry(Polygon, 4326),
  preview_url text,
  constraint plots_name_not_blank check (char_length(btrim(name)) > 0),
  constraint plots_area_positive check (area_rai > 0),
  constraint plots_place_ids_positive check (province_id > 0 and district_id > 0 and subdistrict_id > 0),
  constraint plots_boundary_valid check (boundary is null or extensions.st_isvalid(boundary)),
  constraint plots_preview_url_http check (preview_url is null or preview_url ~ '^https?://')
);

create table public.plantings (
  id uuid primary key default gen_random_uuid(),
  plot_id uuid not null references public.plots (id) on delete cascade,
  variety_id bigint not null references public.varieties (id),
  planted_on date not null,
  harvest_on date not null,
  est_kg integer not null,
  constraint plantings_harvest_after_plant check (harvest_on >= planted_on),
  constraint plantings_est_kg_nonnegative check (est_kg >= 0)
);

create index farmers_group_id_idx on public.farmers (group_id);
create index farmers_province_id_idx on public.farmers (province_id);
create index plots_farmer_id_idx on public.plots (farmer_id);
create index plots_province_id_idx on public.plots (province_id);
create index plots_boundary_idx on public.plots using gist (boundary);
create index plantings_plot_id_idx on public.plantings (plot_id);
create index plantings_variety_id_idx on public.plantings (variety_id);
create unique index plantings_one_per_plot on public.plantings (plot_id);

-- Mill intake: farmer-level, not tied to a plot.
create table public.mill_receipts (
  id uuid primary key default gen_random_uuid(),
  farmer_id uuid not null references public.farmers (id) on delete restrict,
  variety_id bigint not null references public.varieties (id),
  kg integer not null,
  received_on date not null,
  created_at timestamptz not null default now(),
  constraint mill_receipts_kg_positive check (kg > 0)
);

create index mill_receipts_farmer_id_idx on public.mill_receipts (farmer_id);
create index mill_receipts_variety_id_idx on public.mill_receipts (variety_id);
create index mill_receipts_received_on_idx on public.mill_receipts (received_on desc, id desc);

create table public.plot_activities (
  id uuid primary key default gen_random_uuid(),
  planting_id uuid not null references public.plantings (id) on delete cascade,
  type text not null,
  occurred_on date not null,
  payload jsonb not null default '{}'::jsonb,
  note text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint plot_activities_type_check check (
    type in (
      'seed_receive',
      'plant_actual',
      'fertilizer_receive',
      'fertilizer_apply',
      'chemical',
      'problem'
    )
  )
);

create index plot_activities_planting_id_idx on public.plot_activities (planting_id);
create index plot_activities_occurred_on_idx on public.plot_activities (occurred_on, created_at);

create table public.permissions (
  role_id bigint not null references public.roles (id),
  resource text not null,
  scope text not null,
  can_read boolean not null,
  can_add boolean not null,
  can_edit boolean not null,
  can_delete boolean not null,
  primary key (role_id, resource),
  constraint permissions_resource check (resource in ('groups', 'farmers', 'plots', 'plantings', 'activities')),
  constraint permissions_scope check (scope in ('all', 'group', 'own'))
);

create table public.role_grants (
  farmer_id uuid primary key references public.farmers (id) on delete cascade,
  role_id bigint not null references public.roles (id)
);

-- Mill staff login only (username + password).
-- Farmers/members do not use this table — they enter phone (farmers.tel) on the farmer app.
create table public.accounts (
  id uuid primary key default gen_random_uuid(),
  username text not null,
  password_hash text not null,
  display_name text not null,
  role_id bigint not null references public.roles (id) default 1,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  constraint accounts_username_not_blank check (char_length(btrim(username)) > 0),
  constraint accounts_username_unique unique (username),
  constraint accounts_password_hash_not_blank check (char_length(btrim(password_hash)) > 0),
  constraint accounts_display_name_not_blank check (char_length(btrim(display_name)) > 0),
  constraint accounts_mill_role_only check (role_id = 1)
);

create index accounts_role_id_idx on public.accounts (role_id);
